export const GET_MENU_DATA = 'GET_MENU_DATA';
export type GET_MENU_DATA = typeof GET_MENU_DATA;

export const INITIALIZE_PARLIAMENTARY_ELECTION = 'INITIALIZE_PARLIAMENTARY_ELECTION';
export type INITIALIZE_PARLIAMENTARY_ELECTION = typeof INITIALIZE_PARLIAMENTARY_ELECTION;

export const UPDATE_CALCULATION = 'UPDATE_CALCULATION';
export type UPDATE_CALCULATION = typeof UPDATE_CALCULATION;